name: Dart_Web_Server
description: A hello world web server built using the shelf package.
version: 1.0.0
author: Dhananjayan P N

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  shelf: ^1.0.0
  shelf_static: ^1.0.0
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
